# Generated by Django 6.0.2 on 2026-03-09 21:52

import uuid
from django.db import migrations, models


def seed_default_roles(apps, schema_editor):
    SignatureRole = apps.get_model('signatures', 'SignatureRole')
    defaults = [
        ('staff', 'Staff', 'General staff member'),
        ('admin', 'Admin', 'Administrator with full access'),
        ('manager', 'Manager', 'Department or project manager'),
        ('director', 'Director', 'Division or department director'),
    ]
    for key, label, description in defaults:
        SignatureRole.objects.get_or_create(
            key=key,
            defaults={'label': label, 'description': description},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(help_text='Machine-readable identifier (e.g. "director").', max_length=25, unique=True, verbose_name='key')),
                ('label', models.CharField(help_text='Human-readable name (e.g. "Director").', max_length=100, verbose_name='label')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Signature Role',
                'verbose_name_plural': 'Signature Roles',
                'ordering': ['label'],
            },
        ),
        migrations.RunPython(seed_default_roles, migrations.RunPython.noop),
    ]
