# Generated by Django 6.0.3 on 2026-04-26 21:36

import django.core.validators
import keel.security.scanning
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0004_notification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='channel_boswell',
            field=models.BooleanField(default=False, verbose_name='OpenClaw notifications'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('status_change', 'Status Change'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('login', 'Login'), ('export', 'Export'), ('view', 'View'), ('login_failed', 'Login Failed'), ('security_event', 'Security Event'), ('archive', 'Archive'), ('unarchive', 'Unarchive')], max_length=25),
        ),
        migrations.AlterField(
            model_name='signaturedocument',
            name='file',
            field=models.FileField(upload_to='signatures/templates/', validators=[keel.security.scanning.FileSecurityValidator()], verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='signingpacket',
            name='signed_document',
            field=models.FileField(blank=True, null=True, upload_to='signatures/signed/', validators=[keel.security.scanning.FileSecurityValidator()], verbose_name='signed document'),
        ),
        migrations.AlterField(
            model_name='signingstep',
            name='signature_image',
            field=models.FileField(blank=True, help_text='Uploaded or drawn signature image (PNG).', null=True, upload_to='signatures/captured/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])], verbose_name='signature image'),
        ),
        migrations.AlterField(
            model_name='usersignature',
            name='signature_image',
            field=models.FileField(blank=True, null=True, upload_to='signatures/saved/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'bmp', 'webp'])], verbose_name='signature image'),
        ),
    ]
