# Generated by Django 6.0.2 on 2026-03-01 01:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('grants', '0009_alter_grantprogram_application_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signature_flows', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('grant_program', models.ForeignKey(blank=True, help_text='Link to a grant program (leave blank for standalone use).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_flows', to='grants.grantprogram', verbose_name='grant program')),
            ],
            options={
                'verbose_name': 'Signature Flow',
                'verbose_name_plural': 'Signature Flows',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SignatureDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('file', models.FileField(upload_to='signatures/templates/', verbose_name='file')),
                ('page_count', models.PositiveIntegerField(default=0, help_text='Auto-populated on upload.', verbose_name='page count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signature_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='signatures.signatureflow', verbose_name='flow')),
            ],
            options={
                'verbose_name': 'Signature Document',
                'verbose_name_plural': 'Signature Documents',
                'ordering': ['flow', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SignatureFlowStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Execution order (1 = first signer).', verbose_name='order')),
                ('label', models.CharField(help_text='e.g. "Program Officer Approval", "Division Director Sign-off"', max_length=255, verbose_name='label')),
                ('assignment_type', models.CharField(choices=[('user', 'Specific User'), ('role', 'Role')], default='role', max_length=10, verbose_name='assignment type')),
                ('assigned_role', models.CharField(blank=True, default='', help_text='Role key from User.Role (when assignment type is "role").', max_length=25, verbose_name='assigned role')),
                ('is_required', models.BooleanField(default=True, verbose_name='required')),
                ('assigned_user', models.ForeignKey(blank=True, help_text='Specific user (when assignment type is "user").', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flow_steps', to=settings.AUTH_USER_MODEL, verbose_name='assigned user')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='signatures.signatureflow', verbose_name='flow')),
            ],
            options={
                'verbose_name': 'Signature Flow Step',
                'verbose_name_plural': 'Signature Flow Steps',
                'ordering': ['flow', 'order'],
                'unique_together': {('flow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='SignaturePlacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('signature', 'Signature'), ('initials', 'Initials'), ('date', 'Date Signed'), ('name', 'Printed Name')], default='signature', max_length=15, verbose_name='field type')),
                ('page_number', models.PositiveIntegerField(help_text='1-indexed page number.', verbose_name='page number')),
                ('x', models.FloatField(help_text='X position as percentage of page width (0-100).', verbose_name='X position')),
                ('y', models.FloatField(help_text='Y position as percentage of page height (0-100).', verbose_name='Y position')),
                ('width', models.FloatField(default=20.0, help_text='Width as percentage of page width.', verbose_name='width')),
                ('height', models.FloatField(default=5.0, help_text='Height as percentage of page height.', verbose_name='height')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='signatures.signaturedocument', verbose_name='document')),
                ('step', models.ForeignKey(help_text='Which signer step this placement belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='signatures.signatureflowstep', verbose_name='step')),
            ],
            options={
                'verbose_name': 'Signature Placement',
                'verbose_name_plural': 'Signature Placements',
                'ordering': ['document', 'page_number', 'y', 'x'],
            },
        ),
        migrations.CreateModel(
            name='SigningPacket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, default='', max_length=255, verbose_name='object ID')),
                ('title', models.CharField(help_text='Descriptive title for this signing session.', max_length=255, verbose_name='title')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('declined', 'Declined')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('signed_document', models.FileField(blank=True, null=True, upload_to='signatures/signed/', verbose_name='signed document')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('cancel_reason', models.TextField(blank=True, default='', verbose_name='cancel reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_signing_packets', to=settings.AUTH_USER_MODEL, verbose_name='cancelled by')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='content type')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packets', to='signatures.signatureflow', verbose_name='flow')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_signing_packets', to=settings.AUTH_USER_MODEL, verbose_name='initiated by')),
            ],
            options={
                'verbose_name': 'Signing Packet',
                'verbose_name_plural': 'Signing Packets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SigningStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(verbose_name='order')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('signed', 'Signed'), ('declined', 'Declined'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=15, verbose_name='status')),
                ('signature_type', models.CharField(blank=True, choices=[('typed', 'Typed'), ('uploaded', 'Uploaded Image'), ('drawn', 'Drawn')], default='', max_length=10, verbose_name='signature type')),
                ('typed_name', models.CharField(blank=True, default='', help_text='Name typed as signature.', max_length=255, verbose_name='typed name')),
                ('signature_image', models.FileField(blank=True, help_text='Uploaded or drawn signature image (PNG).', null=True, upload_to='signatures/captured/', verbose_name='signature image')),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='signed at')),
                ('signed_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='signed IP')),
                ('declined_at', models.DateTimeField(blank=True, null=True, verbose_name='declined at')),
                ('decline_reason', models.TextField(blank=True, default='', verbose_name='decline reason')),
                ('reminded_at', models.DateTimeField(blank=True, help_text='Last time a reminder email was sent.', null=True, verbose_name='reminded at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signing_steps', to='signatures.signatureflowstep', verbose_name='flow step')),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='signatures.signingpacket', verbose_name='packet')),
                ('signer', models.ForeignKey(help_text='User assigned to sign at this step.', on_delete=django.db.models.deletion.PROTECT, related_name='signing_steps', to=settings.AUTH_USER_MODEL, verbose_name='signer')),
            ],
            options={
                'verbose_name': 'Signing Step',
                'verbose_name_plural': 'Signing Steps',
                'ordering': ['packet', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(default='Default', help_text='Label for this signature (e.g. "Formal", "Initials").', max_length=100, verbose_name='label')),
                ('signature_type', models.CharField(choices=[('typed', 'Typed'), ('uploaded', 'Uploaded Image'), ('drawn', 'Drawn')], max_length=10, verbose_name='signature type')),
                ('typed_name', models.CharField(blank=True, default='', max_length=255, verbose_name='typed name')),
                ('signature_image', models.FileField(blank=True, null=True, upload_to='signatures/saved/', verbose_name='signature image')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_signatures', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User Signature',
                'verbose_name_plural': 'User Signatures',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='signingpacket',
            index=models.Index(fields=['content_type', 'object_id'], name='idx_packet_entity'),
        ),
        migrations.AddIndex(
            model_name='signingpacket',
            index=models.Index(fields=['status', 'created_at'], name='idx_packet_status'),
        ),
        migrations.AddIndex(
            model_name='signingstep',
            index=models.Index(fields=['signer', 'status'], name='idx_signstep_signer_status'),
        ),
    ]
